site_name: SNS-Docs
repo_url: https://github.com/imLudwig/sns-docs/
edit_uri: docs/
site_author: Ludwig
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select





